"""Markdown report generation."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from autogpumd.analysis import THERMO_CANDIDATES, find_first, read_thermo, summarize_thermo


def generate_report(workdir: str | Path) -> Path:
    workdir = Path(workdir)
    report_path = workdir / "report.md"
    is_mock = (workdir / "MOCK_MODE.md").exists() or (workdir / "thermo_mock.csv").exists()
    data_mode = "MOCK" if is_mock else "REAL / USER-PROVIDED"

    thermo_summary = None
    try:
        thermo_summary = summarize_thermo(read_thermo(find_first(workdir, THERMO_CANDIDATES)))
    except (FileNotFoundError, ValueError):
        thermo_summary = None

    diffusion = None
    diffusion_csv = workdir / "analysis" / "diffusion.csv"
    if diffusion_csv.exists():
        diffusion = float(pd.read_csv(diffusion_csv)["diffusion_A2_per_ps"].iloc[0])

    lines = [
        "# AutoGPUMD Workflow Report",
        "",
        f"**Data mode: {data_mode}.**",
        "",
        "## Overview",
        "",
        "AutoGPUMD is an unofficial learning/demo workflow layer around GPUMD/NEP.",
        "It automates lightweight setup, execution, analysis, plotting, and Markdown reporting.",
        "",
        "## Data provenance",
        "",
        (
            "This report uses deterministic synthetic mock data generated by AutoGPUMD. "
            "These data are useful for workflow testing only and are not physical GPUMD/NEP "
            "simulation results."
            if is_mock
            else "This report uses files present in the work directory and treats them as "
            "user-provided or externally generated simulation outputs. Verify GPUMD version, "
            "input files, potential provenance, and output provenance before citation."
        ),
        "",
        "## System",
        "",
        "- Structure input: `structure.xyz` when present.",
        "- Run template: `run.in` when present.",
        "- Potential: user-provided `nep.txt` is required for real GPUMD runs.",
        "",
        "## Simulation settings",
        "",
        "The MVP records settings in `run.in` comments and keeps GPUMD syntax validation outside scope.",
        "",
        "## Thermodynamic stability",
        "",
    ]
    if thermo_summary:
        lines.extend(
            [
                f"- Samples: {thermo_summary['n_samples']:.0f}",
                f"- Mean temperature: {thermo_summary['temperature_mean_K']:.2f} K",
                f"- Temperature standard deviation: {thermo_summary['temperature_std_K']:.2f} K",
                f"- Total energy drift: {thermo_summary['total_energy_drift_eV']:.4f} eV",
                "",
                "![Temperature](figures/temperature.png)",
                "",
                "![Energy](figures/energy.png)",
                "",
            ]
        )
    else:
        lines.extend(["Thermodynamic output was not available or could not be parsed.", ""])

    lines.extend(
        [
            "## RDF observations",
            "",
            (
                "RDF data and figure were generated from the supported XYZ trajectory parser. "
                + (
                    "For mock mode, this illustrates the analysis pipeline rather than a physical "
                    "pair-correlation result."
                    if is_mock
                    else "Interpretation depends on the provenance and quality of the input trajectory."
                )
                if (workdir / "analysis" / "rdf.csv").exists()
                else "RDF analysis was not available."
            ),
            "",
        ]
    )
    if (workdir / "figures" / "rdf.png").exists():
        lines.extend(["![RDF](figures/rdf.png)", ""])

    lines.extend(["## MSD and diffusion observations", ""])
    if diffusion is not None:
        lines.append(f"- Estimated diffusion slope proxy: {diffusion:.6f} Angstrom^2/ps")
        if is_mock:
            lines.append("- Mock-mode MSD is synthetic and should not be read as a real diffusivity.")
    else:
        lines.append("MSD/diffusion analysis was not available.")
    lines.append("")
    if (workdir / "figures" / "msd.png").exists():
        lines.extend(["![MSD](figures/msd.png)", ""])

    lines.extend(
        [
            "## Limitations",
            "",
            "- This is not a replacement for GPUMD, gpyumd, GPUMDkit, or official GPUMD tooling.",
            "- Mock data are synthetic and intended only for workflow validation.",
            "- The parser supports AutoGPUMD mock CSV and simple XYZ/extended XYZ trajectories.",
            "- Real NEP potentials are never fabricated by this project.",
            "",
            "## Next steps",
            "",
            "- Real GPUMD/NEP tutorial-level run.",
            "- NEP training mini-demo.",
            "- High-temperature diffusion case study.",
            "- Confined-system case study.",
            "- Slurm/A800 cluster integration.",
            "- MCP server integration.",
            "",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path
