"""Project and GPUMD template writers."""

from __future__ import annotations

from pathlib import Path

from autogpumd.config import WorkflowConfig


def init_project(project_dir: Path, template: str = "al-nvt", force: bool = False) -> list[Path]:
    if template != "al-nvt":
        raise ValueError("Only template 'al-nvt' is available in the MVP.")

    project_dir.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    for subdir in ("figures", "analysis"):
        path = project_dir / subdir
        path.mkdir(parents=True, exist_ok=True)
        created.append(path)

    readme = project_dir / "README.md"
    if _write_text(
        readme,
        "\n".join(
            [
                "# Al NVT AutoGPUMD Demo",
                "",
                "This folder is a lightweight AutoGPUMD workflow workspace.",
                "Mock mode runs without GPUMD, a GPU, or a real NEP potential.",
                "Real GPUMD runs require a valid GPUMD installation and a user-provided `nep.txt`.",
                "",
            ]
        ),
        force=force,
    ):
        created.append(readme)
    return created


def write_run_in(config: WorkflowConfig, workdir: Path, mock: bool = False) -> Path:
    """Write a conservative run.in template with intentionally limited assumptions."""
    sim = config.simulation
    path = workdir / "run.in"
    lines = [
        "# AutoGPUMD MVP run.in template",
        "# This file is intentionally conservative and may need editing for real GPUMD use.",
        "# Verify syntax against the GPUMD version and examples you use.",
        "",
        f"# potential: {config.potential.path}",
        f"# structure: structure.xyz generated by ASE ({config.structure.symbol})",
        f"# ensemble: {sim.ensemble}",
        f"# temperature_K: {sim.temperature:g}",
        f"# timestep_fs: {sim.timestep_fs:g}",
        f"# equilibration_steps: {sim.equilibration_steps}",
        f"# production_steps: {sim.production_steps}",
        f"# dump_interval: {sim.dump_interval}",
        "",
    ]
    if mock:
        lines.extend(
            [
                "# Mock mode note:",
                "# AutoGPUMD will not pass this file to GPUMD in mock mode.",
                "# Synthetic outputs are generated for analysis and reporting tests.",
            ]
        )
    else:
        lines.extend(
            [
                "# Real mode note:",
                "# Fill in or validate GPUMD commands using official documentation/examples.",
                "# AutoGPUMD does not invent or validate undocumented GPUMD syntax.",
            ]
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_mock_notes(config: WorkflowConfig, workdir: Path) -> Path:
    path = workdir / "MOCK_MODE.md"
    path.write_text(
        "\n".join(
            [
                "# Mock mode",
                "",
                "This workspace was prepared for deterministic synthetic data generation.",
                "No GPUMD executable, GPU, or real NEP potential is required.",
                f"The configured potential path is `{config.potential.path}` and is not used in mock mode.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return path


def _write_text(path: Path, text: str, force: bool = False) -> bool:
    if path.exists() and not force:
        return False
    path.write_text(text, encoding="utf-8")
    return True
